input_list=("3577A_S3_" "3577B_S4_" "MC1A_S1_" "MC1B_S2_")
fastq_directory=fastq_run8-150
output_dir=kraken2-results_run8-150_5prime-trimmed
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48
#kraken_results=kraken2-results_run11_5prime-trimmed/PlusPF
#read_directory=run9_nonhuman-reads