input_list=("2978d_S3_" "2978Td_S4_" "3153d_S1_" "3153Td_S2_")
fastq_directory=run18_fastq
output_dir=kraken2-results_run18_5prime-trimmed
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48
#kraken_results=kraken2-results_run11_5prime-trimmed/PlusPF
#read_directory=run9_nonhuman-reads