input_list=("1512_S2_" "3422_S1_" "3735_S3_" "3738_S4_")
fastq_directory=fastq_run14
output_dir=kraken2-results_run14_5prime-trimmed
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48
#kraken_results=kraken2-results_run11_5prime-trimmed/PlusPF
#read_directory=run9_nonhuman-reads