input_list=("cut150_1512_S2_" "cut150_3422_S1_" "cut150_3735_S3_" "cut150_3738_S4_")
fastq_directory=run14_fastq
output_dir=kraken2-results_run14-cut150_5prime-trimmed
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48
#kraken_results=kraken2-results_run11_5prime-trimmed/PlusPF
#read_directory=run9_nonhuman-reads