input_list=("MC520_S1_" "MC530_S3_" "MC5T20_S2_" "MC5T30_S4_")
fastq_directory=run10_nonhuman-reads
output_dir=kraken2-results_run10_5prime-trimmed
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48
kraken_results=kraken2-results_run11_5prime-trimmed/PlusPF
read_directory=run11_nonhuman-reads