input_list=("MC6A_S1_" "MC6AT_S2_" "MC6B_S3_" "MC6BT_S4_")
fastq_directory=fastq_run11
output_dir=kraken2-results_run11
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48