input_list=("2971_S1_" "2971T_S2_" "2978_S3_" "2978T_S4_")
fastq_directory=fastq_run16
output_dir=kraken2-results_run16_5prime-trimmed
kraken_output_dir=PlusPF
kraken_output_dir_2=EuPathDB48
kraken2_db=Kraken2_db/PlusPF
kraken2_db_2=Kraken2_db/EuPathDB48
#kraken_results=kraken2-results_run11_5prime-trimmed/PlusPF
#read_directory=run9_nonhuman-reads